argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    admin:
      password: admin
    service:
      type: NodePort
      nodePorts:
        http: 30080
